spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_and_java
         ?useSSL=false
         &serverTimezone=UTC
         &allowPublicKeyRetrieval=true

    username: root
    password: 2012
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true