spring:
  application:
    name: rest-with-spring-boot-and-java
  profiles:
    active: dev

logging:
  level:
    # root: warn
    com.github.dcassianodias: debug

  spring-doc:
    paths-to-match: /api/**/v1/**
    swagger-ui:
      use-root-path: true